export const stats = [
  {
    label: "Total Donations",
    value: "$48,500",
    description: "Across all campaigns",
    change: "+12.5%",
    trend: "up" as const,
    icon: "donation",
  },
  {
    label: "Total Expenses",
    value: "$32,200",
    description: "Food & logistics",
    change: "+8.2%",
    trend: "up" as const,
    icon: "expense",
  },
  {
    label: "Remaining Balance",
    value: "$16,300",
    description: "Available funds",
    change: "+4.1%",
    trend: "up" as const,
    icon: "balance",
  },
  {
    label: "People Served",
    value: "12,450",
    description: "Community members",
    change: "+18.3%",
    trend: "up" as const,
    icon: "people",
  },
  {
    label: "Meals Prepared",
    value: "38,200",
    description: "Iftar meals total",
    change: "+22.7%",
    trend: "up" as const,
    icon: "meals",
  },
  {
    label: "Campaign Progress",
    value: "78%",
    description: "Goal: 50,000 meals",
    change: "+5.4%",
    trend: "up" as const,
    icon: "campaign",
  },
];

export const donationsOverview = [
  { month: "Jan", amount: 4200 },
  { month: "Feb", amount: 5800 },
  { month: "Mar", amount: 8900 },
  { month: "Apr", amount: 12400 },
  { month: "May", amount: 7600 },
  { month: "Jun", amount: 9600 },
];

export const expensesOverview = [
  { month: "Jan", amount: 2800 },
  { month: "Feb", amount: 3400 },
  { month: "Mar", amount: 5200 },
  { month: "Apr", amount: 8100 },
  { month: "May", amount: 6300 },
  { month: "Jun", amount: 6400 },
];

export const weeklyActivity = [
  { day: "Mon", donations: 12, expenses: 8, meals: 45 },
  { day: "Tue", donations: 19, expenses: 14, meals: 62 },
  { day: "Wed", donations: 8, expenses: 11, meals: 38 },
  { day: "Thu", donations: 24, expenses: 18, meals: 78 },
  { day: "Fri", donations: 31, expenses: 12, meals: 95 },
  { day: "Sat", donations: 22, expenses: 16, meals: 82 },
  { day: "Sun", donations: 15, expenses: 9, meals: 55 },
];

export const recentActivities = [
  {
    date: "Jul 23, 2026",
    activity: "Iftar meal distribution",
    user: "Ahmed Hassan",
    status: "completed",
  },
  {
    date: "Jul 23, 2026",
    activity: "New donation received - $500",
    user: "Fatima Ali",
    status: "completed",
  },
  {
    date: "Jul 22, 2026",
    activity: "Food supply purchase",
    user: "Omar Mohamed",
    status: "in_progress",
  },
  {
    date: "Jul 22, 2026",
    activity: "Volunteer team assignment",
    user: "Amina Yusuf",
    status: "completed",
  },
  {
    date: "Jul 21, 2026",
    activity: "Daily report submitted",
    user: "Hassan Abdi",
    status: "completed",
  },
  {
    date: "Jul 21, 2026",
    activity: "Gallery photos uploaded",
    user: "Sara Ibrahim",
    status: "completed",
  },
  {
    date: "Jul 20, 2026",
    activity: "Expense report approved",
    user: "Ahmed Hassan",
    status: "completed",
  },
];

export const todaysTasks = [
  {
    task: "Prepare Iftar meals for Block A",
    assignedTo: "Team Alpha",
    priority: "high",
    status: "in_progress",
  },
  {
    task: "Collect morning donations",
    assignedTo: "Fatima Ali",
    priority: "medium",
    status: "pending",
  },
  {
    task: "Distribute food packages",
    assignedTo: "Team Beta",
    priority: "high",
    status: "pending",
  },
  {
    task: "Update daily expense report",
    assignedTo: "Omar Mohamed",
    priority: "low",
    status: "completed",
  },
  {
    task: "Photograph distribution event",
    assignedTo: "Sara Ibrahim",
    priority: "medium",
    status: "pending",
  },
];

export const announcements = [
  {
    id: 1,
    title: "Special Iftar Night - July 25th",
    description:
      "We are organizing a community-wide Iftar night for 500 families. Volunteers needed for preparation starting at 2 PM.",
    date: "Jul 23, 2026",
    type: "event",
  },
  {
    id: 2,
    title: "New Donation Target Reached!",
    description:
      "Alhamdulillah, we have reached 78% of our monthly donation goal. Keep up the great work, community!",
    date: "Jul 22, 2026",
    type: "milestone",
  },
  {
    id: 3,
    title: "Volunteer Training Session",
    description:
      "Mandatory training for new volunteers this Thursday at 10 AM in the main hall.",
    date: "Jul 21, 2026",
    type: "info",
  },
];

export const galleryImages = [
  { id: 1, alt: "Iftar meal preparation", color: "bg-green-200" },
  { id: 2, alt: "Food distribution", color: "bg-gold-200" },
  { id: 3, alt: "Community gathering", color: "bg-green-300" },
  { id: 4, alt: "Volunteer team", color: "bg-gold-100" },
  { id: 5, alt: "Donation sorting", color: "bg-green-100" },
  { id: 6, alt: "Evening Iftar", color: "bg-gold-200" },
];

export interface User {
  id: number;
  fullName: string;
  username: string;
  phone: string;
  role: "Manager" | "Leader" | "Volunteer";
  status: "Active" | "Inactive";
  createdAt: string;
  initials: string;
  color: string;
}

export const users: User[] = [
  {
    id: 1,
    fullName: "Ahmed Hassan",
    username: "ahmed.hassan",
    phone: "+252 61 234 5678",
    role: "Manager",
    status: "Active",
    createdAt: "Jan 10, 2026",
    initials: "AH",
    color: "from-green-500 to-green-600",
  },
  {
    id: 2,
    fullName: "Fatima Ali",
    username: "fatima.ali",
    phone: "+252 62 345 6789",
    role: "Leader",
    status: "Active",
    createdAt: "Jan 15, 2026",
    initials: "FA",
    color: "from-gold-400 to-gold-500",
  },
  {
    id: 3,
    fullName: "Omar Mohamed",
    username: "omar.mohamed",
    phone: "+252 63 456 7890",
    role: "Volunteer",
    status: "Active",
    createdAt: "Feb 01, 2026",
    initials: "OM",
    color: "from-blue-400 to-blue-500",
  },
  {
    id: 4,
    fullName: "Amina Yusuf",
    username: "amina.yusuf",
    phone: "+252 61 567 8901",
    role: "Leader",
    status: "Active",
    createdAt: "Feb 10, 2026",
    initials: "AY",
    color: "from-gold-400 to-gold-500",
  },
  {
    id: 5,
    fullName: "Hassan Abdi",
    username: "hassan.abdi",
    phone: "+252 62 678 9012",
    role: "Volunteer",
    status: "Inactive",
    createdAt: "Feb 20, 2026",
    initials: "HA",
    color: "from-blue-400 to-blue-500",
  },
  {
    id: 6,
    fullName: "Sara Ibrahim",
    username: "sara.ibrahim",
    phone: "+252 63 789 0123",
    role: "Volunteer",
    status: "Active",
    createdAt: "Mar 01, 2026",
    initials: "SI",
    color: "from-blue-400 to-blue-500",
  },
  {
    id: 7,
    fullName: "Khalid Osman",
    username: "khalid.osman",
    phone: "+252 61 890 1234",
    role: "Manager",
    status: "Active",
    createdAt: "Mar 05, 2026",
    initials: "KO",
    color: "from-green-500 to-green-600",
  },
  {
    id: 8,
    fullName: "Maryam Said",
    username: "maryam.said",
    phone: "+252 62 901 2345",
    role: "Leader",
    status: "Inactive",
    createdAt: "Mar 12, 2026",
    initials: "MS",
    color: "from-gold-400 to-gold-500",
  },
  {
    id: 9,
    fullName: "Abdirahman Ali",
    username: "abdirahman.ali",
    phone: "+252 63 012 3456",
    role: "Volunteer",
    status: "Active",
    createdAt: "Mar 20, 2026",
    initials: "AA",
    color: "from-blue-400 to-blue-500",
  },
  {
    id: 10,
    fullName: "Hawa Mohamed",
    username: "hawa.mohamed",
    phone: "+252 61 123 4567",
    role: "Volunteer",
    status: "Active",
    createdAt: "Apr 01, 2026",
    initials: "HM",
    color: "from-blue-400 to-blue-500",
  },
  {
    id: 11,
    fullName: "Yusuf Hassan",
    username: "yusuf.hassan",
    phone: "+252 62 234 5678",
    role: "Leader",
    status: "Active",
    createdAt: "Apr 10, 2026",
    initials: "YH",
    color: "from-gold-400 to-gold-500",
  },
  {
    id: 12,
    fullName: "Zahra Abdi",
    username: "zahra.abdi",
    phone: "+252 63 345 6789",
    role: "Volunteer",
    status: "Active",
    createdAt: "Apr 18, 2026",
    initials: "ZA",
    color: "from-blue-400 to-blue-500",
  },
];

export interface Donation {
  id: number;
  receipt: string;
  donorName: string;
  donationType: "Cash" | "In-Kind";
  amount?: number;
  itemName?: string;
  category?: string;
  quantity?: number;
  unit?: string;
  estimatedValue?: number;
  paymentMethod?: string;
  referenceNumber?: string;
  date: string;
  notes?: string;
  status: "Completed" | "Pending" | "Cancelled";
}

export const donations: Donation[] = [
  {
    id: 1,
    receipt: "REC-001",
    donorName: "Ahmed Hassan",
    donationType: "Cash",
    amount: 500,
    paymentMethod: "EVC Plus",
    referenceNumber: "EVC-98765",
    date: "Jul 23, 2026",
    notes: "Monthly Ramadan donation",
    status: "Completed",
  },
  {
    id: 2,
    receipt: "REC-002",
    donorName: "Fatima Ali",
    donationType: "In-Kind",
    itemName: "Rice",
    category: "Rice",
    quantity: 50,
    unit: "kg",
    estimatedValue: 200,
    date: "Jul 23, 2026",
    notes: "Premium basmati rice",
    status: "Completed",
  },
  {
    id: 3,
    receipt: "REC-003",
    donorName: "Omar Mohamed",
    donationType: "Cash",
    amount: 250,
    paymentMethod: "Bank",
    referenceNumber: "BNK-45612",
    date: "Jul 22, 2026",
    status: "Completed",
  },
  {
    id: 4,
    receipt: "REC-004",
    donorName: "Amina Yusuf",
    donationType: "In-Kind",
    itemName: "Cooking Oil",
    category: "Oil",
    quantity: 30,
    unit: "liters",
    estimatedValue: 150,
    date: "Jul 22, 2026",
    status: "Completed",
  },
  {
    id: 5,
    receipt: "REC-005",
    donorName: "Hassan Abdi",
    donationType: "Cash",
    amount: 1000,
    paymentMethod: "Cash",
    date: "Jul 22, 2026",
    notes: "For Iftar night event",
    status: "Completed",
  },
  {
    id: 6,
    receipt: "REC-006",
    donorName: "Sara Ibrahim",
    donationType: "In-Kind",
    itemName: "Dates",
    category: "Dates",
    quantity: 100,
    unit: "kg",
    estimatedValue: 300,
    date: "Jul 21, 2026",
    status: "Completed",
  },
  {
    id: 7,
    receipt: "REC-007",
    donorName: "Khalid Osman",
    donationType: "Cash",
    amount: 750,
    paymentMethod: "EVC Plus",
    referenceNumber: "EVC-34567",
    date: "Jul 21, 2026",
    status: "Pending",
  },
  {
    id: 8,
    receipt: "REC-008",
    donorName: "Maryam Said",
    donationType: "In-Kind",
    itemName: "Sugar",
    category: "Sugar",
    quantity: 40,
    unit: "kg",
    estimatedValue: 120,
    date: "Jul 21, 2026",
    status: "Completed",
  },
  {
    id: 9,
    receipt: "REC-009",
    donorName: "Abdirahman Ali",
    donationType: "Cash",
    amount: 300,
    paymentMethod: "Cash",
    date: "Jul 20, 2026",
    status: "Completed",
  },
  {
    id: 10,
    receipt: "REC-010",
    donorName: "Hawa Mohamed",
    donationType: "In-Kind",
    itemName: "Water",
    category: "Water",
    quantity: 200,
    unit: "bottles",
    estimatedValue: 100,
    date: "Jul 20, 2026",
    status: "Completed",
  },
  {
    id: 11,
    receipt: "REC-011",
    donorName: "Yusuf Hassan",
    donationType: "Cash",
    amount: 1500,
    paymentMethod: "Bank",
    referenceNumber: "BNK-78901",
    date: "Jul 20, 2026",
    notes: "Large contribution for the month",
    status: "Completed",
  },
  {
    id: 12,
    receipt: "REC-012",
    donorName: "Zahra Abdi",
    donationType: "In-Kind",
    itemName: "Flour",
    category: "Flour",
    quantity: 60,
    unit: "kg",
    estimatedValue: 180,
    date: "Jul 19, 2026",
    status: "Completed",
  },
  {
    id: 13,
    receipt: "REC-013",
    donorName: "Ahmed Hassan",
    donationType: "Cash",
    amount: 200,
    paymentMethod: "EVC Plus",
    referenceNumber: "EVC-11223",
    date: "Jul 19, 2026",
    status: "Pending",
  },
  {
    id: 14,
    receipt: "REC-014",
    donorName: "Fatima Ali",
    donationType: "In-Kind",
    itemName: "Meat",
    category: "Meat",
    quantity: 25,
    unit: "kg",
    estimatedValue: 500,
    date: "Jul 18, 2026",
    notes: "Fresh beef for community iftar",
    status: "Completed",
  },
  {
    id: 15,
    receipt: "REC-015",
    donorName: "Omar Mohamed",
    donationType: "Cash",
    amount: 400,
    paymentMethod: "Cash",
    date: "Jul 18, 2026",
    status: "Cancelled",
  },
  {
    id: 16,
    receipt: "REC-016",
    donorName: "Amina Yusuf",
    donationType: "In-Kind",
    itemName: "Juice",
    category: "Juice",
    quantity: 80,
    unit: "cartons",
    estimatedValue: 160,
    date: "Jul 18, 2026",
    status: "Completed",
  },
];

export interface Expense {
  id: number;
  receipt: string;
  name: string;
  category: "Food" | "Transport" | "Packaging" | "Water" | "Cooking" | "Other";
  quantity: number;
  unit: string;
  unitPrice: number;
  totalCost: number;
  paidBy: string;
  paymentMethod: "Cash" | "EVC Plus" | "Bank";
  receiptNumber?: string;
  date: string;
  notes?: string;
  receiptFile?: string;
  status: "Approved" | "Pending" | "Rejected";
}

export const expenses: Expense[] = [
  {
    id: 1,
    receipt: "EXP-001",
    name: "Rice Purchase - Bulk",
    category: "Food",
    quantity: 100,
    unit: "kg",
    unitPrice: 3.5,
    totalCost: 350,
    paidBy: "Ahmed Hassan",
    paymentMethod: "Cash",
    date: "Jul 23, 2026",
    notes: "Premium basmati rice for weekly iftar",
    status: "Approved",
  },
  {
    id: 2,
    receipt: "EXP-002",
    name: "Van Rental - Distribution",
    category: "Transport",
    quantity: 1,
    unit: "trip",
    unitPrice: 80,
    totalCost: 80,
    paidBy: "Omar Mohamed",
    paymentMethod: "Cash",
    receiptNumber: "CASH-4501",
    date: "Jul 23, 2026",
    notes: "Transport food to Block C distribution point",
    status: "Approved",
  },
  {
    id: 3,
    receipt: "EXP-003",
    name: "Cooking Oil - 5L",
    category: "Cooking",
    quantity: 20,
    unit: "liters",
    unitPrice: 8,
    totalCost: 160,
    paidBy: "Fatima Ali",
    paymentMethod: "EVC Plus",
    receiptNumber: "EVC-78234",
    date: "Jul 22, 2026",
    status: "Approved",
  },
  {
    id: 4,
    receipt: "EXP-004",
    name: "Food Packaging Bags",
    category: "Packaging",
    quantity: 500,
    unit: "pieces",
    unitPrice: 0.2,
    totalCost: 100,
    paidBy: "Sara Ibrahim",
    paymentMethod: "Cash",
    date: "Jul 22, 2026",
    notes: "Disposable food containers for iftar meals",
    status: "Approved",
  },
  {
    id: 5,
    receipt: "EXP-005",
    name: "Bottled Water - 1.5L",
    category: "Water",
    quantity: 200,
    unit: "bottles",
    unitPrice: 0.75,
    totalCost: 150,
    paidBy: "Khalid Osman",
    paymentMethod: "Bank",
    receiptNumber: "BNK-22345",
    date: "Jul 22, 2026",
    status: "Pending",
  },
  {
    id: 6,
    receipt: "EXP-006",
    name: "Meat Purchase - Fresh Beef",
    category: "Food",
    quantity: 50,
    unit: "kg",
    unitPrice: 12,
    totalCost: 600,
    paidBy: "Ahmed Hassan",
    paymentMethod: "Cash",
    date: "Jul 21, 2026",
    notes: "Fresh beef for community iftar night",
    status: "Approved",
  },
  {
    id: 7,
    receipt: "EXP-007",
    name: "Taxi Fare - Market Run",
    category: "Transport",
    quantity: 3,
    unit: "trips",
    unitPrice: 15,
    totalCost: 45,
    paidBy: "Amina Yusuf",
    paymentMethod: "Cash",
    date: "Jul 21, 2026",
    status: "Approved",
  },
  {
    id: 8,
    receipt: "EXP-008",
    name: "Propane Gas Tanks",
    category: "Cooking",
    quantity: 4,
    unit: "tanks",
    unitPrice: 25,
    totalCost: 100,
    paidBy: "Omar Mohamed",
    paymentMethod: "EVC Plus",
    receiptNumber: "EVC-55678",
    date: "Jul 21, 2026",
    notes: "For outdoor cooking stations",
    status: "Pending",
  },
  {
    id: 9,
    receipt: "EXP-009",
    name: "Sugar - 25kg Bag",
    category: "Food",
    quantity: 10,
    unit: "bags",
    unitPrice: 18,
    totalCost: 180,
    paidBy: "Fatima Ali",
    paymentMethod: "Cash",
    date: "Jul 20, 2026",
    status: "Approved",
  },
  {
    id: 10,
    receipt: "EXP-010",
    name: "Delivery Truck Fuel",
    category: "Transport",
    quantity: 1,
    unit: "fill-up",
    unitPrice: 65,
    totalCost: 65,
    paidBy: "Hassan Abdi",
    paymentMethod: "EVC Plus",
    receiptNumber: "EVC-88123",
    date: "Jul 20, 2026",
    status: "Approved",
  },
  {
    id: 11,
    receipt: "EXP-011",
    name: "Disposable Plates & Cups",
    category: "Packaging",
    quantity: 300,
    unit: "sets",
    unitPrice: 0.3,
    totalCost: 90,
    paidBy: "Sara Ibrahim",
    paymentMethod: "Cash",
    date: "Jul 20, 2026",
    status: "Approved",
  },
  {
    id: 12,
    receipt: "EXP-012",
    name: "Dates - Premium",
    category: "Food",
    quantity: 30,
    unit: "kg",
    unitPrice: 6,
    totalCost: 180,
    paidBy: "Khalid Osman",
    paymentMethod: "Bank",
    receiptNumber: "BNK-33456",
    date: "Jul 19, 2026",
    notes: "Premium dates for iftar",
    status: "Approved",
  },
  {
    id: 13,
    receipt: "EXP-013",
    name: "Water Tanker Rental",
    category: "Water",
    quantity: 1,
    unit: "day",
    unitPrice: 120,
    totalCost: 120,
    paidBy: "Ahmed Hassan",
    paymentMethod: "Cash",
    date: "Jul 19, 2026",
    status: "Rejected",
  },
  {
    id: 14,
    receipt: "EXP-014",
    name: "Miscellaneous Supplies",
    category: "Other",
    quantity: 1,
    unit: "lot",
    unitPrice: 45,
    totalCost: 45,
    paidBy: "Amina Yusuf",
    paymentMethod: "Cash",
    date: "Jul 19, 2026",
    notes: "Cleaning supplies and utensils",
    status: "Approved",
  },
  {
    id: 15,
    receipt: "EXP-015",
    name: "Flour - 50kg Bag",
    category: "Food",
    quantity: 8,
    unit: "bags",
    unitPrice: 22,
    totalCost: 176,
    paidBy: "Fatima Ali",
    paymentMethod: "EVC Plus",
    receiptNumber: "EVC-99012",
    date: "Jul 18, 2026",
    status: "Approved",
  },
  {
    id: 16,
    receipt: "EXP-016",
    name: "Generator Rental",
    category: "Other",
    quantity: 2,
    unit: "days",
    unitPrice: 50,
    totalCost: 100,
    paidBy: "Omar Mohamed",
    paymentMethod: "Cash",
    date: "Jul 18, 2026",
    notes: "For evening iftar lighting",
    status: "Pending",
  },
];

export interface DailyReport {
  id: number;
  date: string;
  location: string;
  peopleServed: number;
  mealsPrepared: number;
  mealsRemaining: number;
  foodMenu: string;
  teamLeader: string;
  volunteersCount: number;
  weather: string;
  startTime: string;
  endTime: string;
  notes?: string;
  photos: string[];
  videos: string[];
  status: "Completed" | "Pending" | "In Progress";
}

export const dailyReports: DailyReport[] = [
  {
    id: 1,
    date: "Jul 19, 2026",
    location: "Banadir",
    peopleServed: 450,
    mealsPrepared: 500,
    mealsRemaining: 50,
    foodMenu: "Rice, Beef Curry, Dates, Water",
    teamLeader: "Ahmed Hassan",
    volunteersCount: 12,
    weather: "Sunny",
    startTime: "4:30 PM",
    endTime: "8:00 PM",
    notes: "Smooth distribution. Community very grateful. Extra rice served to families with children.",
    photos: ["iftar-block-a-1.jpg", "iftar-block-a-2.jpg", "cooking-block-a.jpg"],
    videos: ["distribution-block-a.mp4"],
    status: "Completed",
  },
  {
    id: 2,
    date: "Jul 20, 2026",
    location: "Banadir",
    peopleServed: 380,
    mealsPrepared: 400,
    mealsRemaining: 20,
    foodMenu: "Pasta, Chicken, Salad, Juice",
    teamLeader: "Fatima Ali",
    volunteersCount: 10,
    weather: "Partly Cloudy",
    startTime: "5:00 PM",
    endTime: "8:30 PM",
    notes: "Good turnout. Some families arrived early. Team managed queue well.",
    photos: ["iftar-block-b-1.jpg", "volunteers-block-b.jpg"],
    videos: ["iftar-block-b.mp4"],
    status: "Completed",
  },
  {
    id: 3,
    date: "Jul 21, 2026",
    location: "Banadir",
    peopleServed: 520,
    mealsPrepared: 550,
    mealsRemaining: 30,
    foodMenu: "Biryani, Samosas, Fruit Salad, Water",
    teamLeader: "Omar Mohamed",
    volunteersCount: 15,
    weather: "Hot",
    startTime: "4:00 PM",
    endTime: "8:00 PM",
    notes: "Largest turnout so far. Added extra water stations due to heat. All meals distributed successfully.",
    photos: ["iftar-block-c-1.jpg", "iftar-block-c-2.jpg", "crowd-block-c.jpg", "cooking-block-c.jpg"],
    videos: ["distribution-block-c.mp4"],
    status: "Completed",
  },
  {
    id: 4,
    date: "Jul 22, 2026",
    location: "Xamar Bile",
    peopleServed: 0,
    mealsPrepared: 0,
    mealsRemaining: 0,
    foodMenu: "Pending menu planning",
    teamLeader: "Amina Yusuf",
    volunteersCount: 0,
    weather: "Expected: Clear",
    startTime: "5:00 PM",
    endTime: "8:00 PM",
    notes: "Awaiting final volunteer confirmations. Food supplies confirmed.",
    photos: [],
    videos: ["iftar-day4.mp4"],
    status: "Pending",
  },
  {
    id: 5,
    date: "Jul 23, 2026",
    location: "Xamar Bile",
    peopleServed: 0,
    mealsPrepared: 0,
    mealsRemaining: 0,
    foodMenu: "Pending menu planning",
    teamLeader: "Khalid Osman",
    volunteersCount: 0,
    weather: "Expected: Clear",
    startTime: "4:30 PM",
    endTime: "8:00 PM",
    notes: "Final day of campaign. Special Iftar night planned with community gathering.",
    photos: [],
    videos: ["iftar-day5.mp4"],
    status: "Pending",
  },
];

export interface Task {
  id: number;
  name: string;
  description: string;
  assignedTo: string;
  assignedToId: number;
  role: "Manager" | "Leader" | "Volunteer";
  priority: "Low" | "Medium" | "High";
  startDate: string;
  dueDate: string;
  status: "Pending" | "In Progress" | "Completed";
  notes?: string;
  progress: number;
}

export const tasks: Task[] = [
  {
    id: 1,
    name: "Prepare Iftar meals for Block A",
    description: "Cook and package 500 meals for Block A distribution. Rice, beef curry, dates, and water.",
    assignedTo: "Ahmed Hassan",
    assignedToId: 1,
    role: "Manager",
    priority: "High",
    startDate: "Jul 19, 2026",
    dueDate: "Jul 19, 2026",
    status: "Completed",
    notes: "All meals prepared on time. 50 extra meals prepared as buffer.",
    progress: 100,
  },
  {
    id: 2,
    name: "Collect morning donations",
    description: "Visit local businesses and collect monetary and in-kind donations for the campaign.",
    assignedTo: "Fatima Ali",
    assignedToId: 2,
    role: "Leader",
    priority: "Medium",
    startDate: "Jul 20, 2026",
    dueDate: "Jul 20, 2026",
    status: "Completed",
    notes: "Collected $750 cash and 30kg rice from 5 businesses.",
    progress: 100,
  },
  {
    id: 3,
    name: "Distribute food packages",
    description: "Deliver food packages to families in Block B and Block C. Ensure each family receives their allocated portion.",
    assignedTo: "Omar Mohamed",
    assignedToId: 3,
    role: "Volunteer",
    priority: "High",
    startDate: "Jul 21, 2026",
    dueDate: "Jul 21, 2026",
    status: "Completed",
    notes: "All 380 packages delivered successfully. 2 families requested extra rice.",
    progress: 100,
  },
  {
    id: 4,
    name: "Update daily expense report",
    description: "Compile and update the daily expense report with all receipts and transactions from the day.",
    assignedTo: "Sara Ibrahim",
    assignedToId: 4,
    role: "Volunteer",
    priority: "Low",
    startDate: "Jul 22, 2026",
    dueDate: "Jul 22, 2026",
    status: "Completed",
    notes: "All expenses logged. Total spent today: $690.",
    progress: 100,
  },
  {
    id: 5,
    name: "Photograph distribution event",
    description: "Take photos and videos during the distribution event for documentation and social media.",
    assignedTo: "Sara Ibrahim",
    assignedToId: 4,
    role: "Volunteer",
    priority: "Medium",
    startDate: "Jul 22, 2026",
    dueDate: "Jul 22, 2026",
    status: "Completed",
    progress: 100,
  },
  {
    id: 6,
    name: "Coordinate Block D Iftar",
    description: "Set up the school yard for Block D Iftar. Arrange seating, serving stations, and decorations.",
    assignedTo: "Amina Yusuf",
    assignedToId: 5,
    role: "Leader",
    priority: "High",
    startDate: "Jul 22, 2026",
    dueDate: "Jul 22, 2026",
    status: "In Progress",
    notes: "Tables arranged. Waiting for food delivery from kitchen team.",
    progress: 60,
  },
  {
    id: 7,
    name: "Purchase cooking supplies",
    description: "Buy additional cooking oil, spices, and disposable plates from the local market.",
    assignedTo: "Khalid Osman",
    assignedToId: 6,
    role: "Manager",
    priority: "Medium",
    startDate: "Jul 22, 2026",
    dueDate: "Jul 23, 2026",
    status: "In Progress",
    notes: "Oil and plates purchased. Still need spices.",
    progress: 40,
  },
  {
    id: 8,
    name: "Volunteer team briefing",
    description: "Brief all volunteers on tomorrow's tasks, safety protocols, and distribution plan.",
    assignedTo: "Ahmed Hassan",
    assignedToId: 1,
    role: "Manager",
    priority: "High",
    startDate: "Jul 23, 2026",
    dueDate: "Jul 23, 2026",
    status: "Pending",
    notes: "Scheduled for 2:00 PM before Iftar.",
    progress: 0,
  },
  {
    id: 9,
    name: "Finalize Block E Park setup",
    description: "Prepare the park area for the final campaign day Iftar night. Stage, lights, and seating.",
    assignedTo: "Khalid Osman",
    assignedToId: 6,
    role: "Manager",
    priority: "High",
    startDate: "Jul 23, 2026",
    dueDate: "Jul 23, 2026",
    status: "Pending",
    notes: "Generator rental confirmed. Light setup team assigned.",
    progress: 0,
  },
  {
    id: 10,
    name: "Submit final campaign report",
    description: "Compile all daily reports, expense summaries, and photo documentation into the final campaign report.",
    assignedTo: "Fatima Ali",
    assignedToId: 2,
    role: "Leader",
    priority: "Medium",
    startDate: "Jul 23, 2026",
    dueDate: "Jul 24, 2026",
    status: "Pending",
    progress: 0,
  },
  {
    id: 11,
    name: "Clean up Block C area",
    description: "Clean and restore the open area after the distribution event. Dispose of waste properly.",
    assignedTo: "Hassan Abdi",
    assignedToId: 7,
    role: "Volunteer",
    priority: "Low",
    startDate: "Jul 21, 2026",
    dueDate: "Jul 21, 2026",
    status: "Completed",
    progress: 100,
  },
  {
    id: 12,
    name: "Arrange water stations",
    description: "Set up water stations at all distribution points. Ensure adequate supply and cups.",
    assignedTo: "Abdirahman Ali",
    assignedToId: 8,
    role: "Volunteer",
    priority: "Medium",
    startDate: "Jul 20, 2026",
    dueDate: "Jul 20, 2026",
    status: "Completed",
    progress: 100,
  },
  {
    id: 13,
    name: "Prepare special Iftar menu",
    description: "Plan and prepare the special menu for the final community Iftar night. Biryani, desserts, and drinks.",
    assignedTo: "Fatima Ali",
    assignedToId: 2,
    role: "Leader",
    priority: "High",
    startDate: "Jul 23, 2026",
    dueDate: "Jul 23, 2026",
    status: "Pending",
    notes: "Menu approved. Ingredients ordered.",
    progress: 0,
  },
  {
    id: 14,
    name: "Transport equipment to Park",
    description: "Move tables, chairs, and serving equipment from storage to the park venue.",
    assignedTo: "Omar Mohamed",
    assignedToId: 3,
    role: "Volunteer",
    priority: "Medium",
    startDate: "Jul 23, 2026",
    dueDate: "Jul 23, 2026",
    status: "Pending",
    progress: 0,
  },
  {
    id: 15,
    name: "Update social media posts",
    description: "Post campaign updates, photos, and thank-you messages on social media platforms.",
    assignedTo: "Maryam Said",
    assignedToId: 9,
    role: "Volunteer",
    priority: "Low",
    startDate: "Jul 19, 2026",
    dueDate: "Jul 23, 2026",
    status: "In Progress",
    notes: "Daily posts scheduled. Engagement is good.",
    progress: 70,
  },
];

export interface GalleryItem {
  id: number;
  type: "Photo" | "Video";
  title: string;
  description: string;
  campaignDay: 1 | 2 | 3 | 4 | 5;
  location: string;
  date: string;
  uploadedBy: string;
  tags: string[];
  color: string;
  size: string;
  duration?: string;
  videoUrl?: string;
  fileName?: string;
}

export const galleryItems: GalleryItem[] = [
  {
    id: 1,
    type: "Photo",
    title: "Iftar Preparation - Block A",
    description: "Volunteers preparing meals in the Block A kitchen.",
    campaignDay: 1,
    location: "Block A - Main Hall",
    date: "Jul 19, 2026",
    uploadedBy: "Sara Ibrahim",
    tags: ["preparation", "kitchen", "volunteers"],
    color: "from-green-200 to-green-300",
    size: "2.4 MB",
  },
  {
    id: 2,
    type: "Photo",
    title: "Community Gathering",
    description: "Community members gathering for Iftar at Block A.",
    campaignDay: 1,
    location: "Block A - Main Hall",
    date: "Jul 19, 2026",
    uploadedBy: "Sara Ibrahim",
    tags: ["community", "iftar", "gathering"],
    color: "from-green-300 to-green-400",
    size: "3.1 MB",
  },
  {
    id: 3,
    type: "Video",
    title: "Food Distribution - Day 1",
    description: "Full video of food distribution at Block A.",
    campaignDay: 1,
    location: "Block A - Main Hall",
    date: "Jul 19, 2026",
    uploadedBy: "Ahmed Hassan",
    tags: ["distribution", "iftar", "block-a"],
    color: "from-gray-700 to-gray-800",
    size: "45.2 MB",
    duration: "12:34",
  },
  {
    id: 4,
    type: "Photo",
    title: "Block B Setup",
    description: "Setting up the serving area at Block B Community Center.",
    campaignDay: 2,
    location: "Block B - Community Center",
    date: "Jul 20, 2026",
    uploadedBy: "Fatima Ali",
    tags: ["setup", "serving", "block-b"],
    color: "from-amber-100 to-amber-200",
    size: "1.8 MB",
  },
  {
    id: 5,
    type: "Photo",
    title: "Volunteer Team - Block B",
    description: "The volunteer team at Block B ready for distribution.",
    campaignDay: 2,
    location: "Block B - Community Center",
    date: "Jul 20, 2026",
    uploadedBy: "Fatima Ali",
    tags: ["volunteers", "team", "block-b"],
    color: "from-blue-100 to-blue-200",
    size: "2.2 MB",
  },
  {
    id: 6,
    type: "Video",
    title: "Iftar Night - Block B",
    description: "Highlights of the Iftar night at Block B.",
    campaignDay: 2,
    location: "Block B - Community Center",
    date: "Jul 20, 2026",
    uploadedBy: "Omar Mohamed",
    tags: ["iftar", "night", "highlights"],
    color: "from-gray-700 to-gray-800",
    size: "52.8 MB",
    duration: "18:22",
  },
  {
    id: 7,
    type: "Photo",
    title: "Block C - Large Crowd",
    description: "Record turnout at Block C open area distribution.",
    campaignDay: 3,
    location: "Block C - Open Area",
    date: "Jul 21, 2026",
    uploadedBy: "Sara Ibrahim",
    tags: ["crowd", "distribution", "block-c"],
    color: "from-purple-100 to-purple-200",
    size: "3.5 MB",
  },
  {
    id: 8,
    type: "Photo",
    title: "Cooking Station - Block C",
    description: "Outdoor cooking stations in action at Block C.",
    campaignDay: 3,
    location: "Block C - Open Area",
    date: "Jul 21, 2026",
    uploadedBy: "Sara Ibrahim",
    tags: ["cooking", "outdoor", "station"],
    color: "from-orange-100 to-orange-200",
    size: "2.8 MB",
  },
  {
    id: 9,
    type: "Photo",
    title: "Water Station Setup",
    description: "Extra water stations set up due to hot weather.",
    campaignDay: 3,
    location: "Block C - Open Area",
    date: "Jul 21, 2026",
    uploadedBy: "Abdirahman Ali",
    tags: ["water", "setup", "hot-weather"],
    color: "from-cyan-100 to-cyan-200",
    size: "1.5 MB",
  },
  {
    id: 10,
    type: "Video",
    title: "Full Distribution - Block C",
    description: "Complete video of the Block C distribution event.",
    campaignDay: 3,
    location: "Block C - Open Area",
    date: "Jul 21, 2026",
    uploadedBy: "Omar Mohamed",
    tags: ["distribution", "full-event", "block-c"],
    color: "from-gray-700 to-gray-800",
    size: "68.4 MB",
    duration: "25:10",
  },
  {
    id: 11,
    type: "Photo",
    title: "Team Briefing",
    description: "Ahmed Hassan briefing the volunteer team.",
    campaignDay: 4,
    location: "Block D - School Yard",
    date: "Jul 22, 2026",
    uploadedBy: "Sara Ibrahim",
    tags: ["briefing", "team", "planning"],
    color: "from-green-100 to-green-200",
    size: "1.9 MB",
  },
  {
    id: 12,
    type: "Photo",
    title: "School Yard Setup",
    description: "Setting up the school yard for Block D Iftar.",
    campaignDay: 4,
    location: "Block D - School Yard",
    date: "Jul 22, 2026",
    uploadedBy: "Amina Yusuf",
    tags: ["setup", "school", "block-d"],
    color: "from-yellow-100 to-yellow-200",
    size: "2.1 MB",
  },
  {
    id: 13,
    type: "Photo",
    title: "Final Day Planning",
    description: "Planning meeting for the final Iftar night at Block E.",
    campaignDay: 5,
    location: "Block E - Park",
    date: "Jul 23, 2026",
    uploadedBy: "Khalid Osman",
    tags: ["planning", "final-day", "park"],
    color: "from-emerald-100 to-emerald-200",
    size: "1.7 MB",
  },
  {
    id: 14,
    type: "Video",
    title: "Campaign Highlights Reel",
    description: "Compilation of the best moments from the entire campaign.",
    campaignDay: 5,
    location: "Various Locations",
    date: "Jul 23, 2026",
    uploadedBy: "Maryam Said",
    tags: ["highlights", "compilation", "campaign"],
    color: "from-gray-700 to-gray-800",
    size: "124.5 MB",
    duration: "5:32",
  },
  {
    id: 15,
    type: "Photo",
    title: "Community Gratitude",
    description: "Community members expressing gratitude for the Iftar program.",
    campaignDay: 1,
    location: "Block A - Main Hall",
    date: "Jul 19, 2026",
    uploadedBy: "Sara Ibrahim",
    tags: ["gratitude", "community", "appreciation"],
    color: "from-pink-100 to-pink-200",
    size: "2.0 MB",
  },
  {
    id: 16,
    type: "Photo",
    title: "Donation Collection",
    description: "Collecting in-kind donations from local businesses.",
    campaignDay: 2,
    location: "Block B - Community Center",
    date: "Jul 20, 2026",
    uploadedBy: "Fatima Ali",
    tags: ["donations", "business", "collection"],
    color: "from-gold-100 to-gold-200",
    size: "2.3 MB",
  },
  {
    id: 17,
    type: "Photo",
    title: "Kids Enjoying Iftar",
    description: "Children enjoying their Iftar meal at Block C.",
    campaignDay: 3,
    location: "Block C - Open Area",
    date: "Jul 21, 2026",
    uploadedBy: "Sara Ibrahim",
    tags: ["kids", "iftar", "joy"],
    color: "from-rose-100 to-rose-200",
    size: "1.6 MB",
  },
  {
    id: 18,
    type: "Video",
    title: "Behind the Scenes - Day 4",
    description: "Behind the scenes footage of the Block D preparation.",
    campaignDay: 4,
    location: "Block D - School Yard",
    date: "Jul 22, 2026",
    uploadedBy: "Omar Mohamed",
    tags: ["behind-the-scenes", "preparation", "block-d"],
    color: "from-gray-700 to-gray-800",
    size: "38.7 MB",
    duration: "10:45",
  },
];

export interface Message {
  id: number;
  senderId: number;
  senderName: string;
  senderInitials: string;
  senderColor: string;
  recipientIds: number[];
  recipientNames: string[];
  recipientRole: string;
  subject: string;
  content: string;
  priority: "Low" | "Medium" | "High" | "Urgent";
  status: "Sent" | "Delivered" | "Read";
  isRead: boolean;
  isPinned: boolean;
  isAnnouncement: boolean;
  date: string;
  time: string;
  attachments: { name: string; type: "image" | "video" | "document"; size: string }[];
  thread: {
    id: number;
    senderId: number;
    senderName: string;
    senderInitials: string;
    senderColor: string;
    content: string;
    date: string;
    time: string;
    isSystem?: boolean;
  }[];
}

export const messages: Message[] = [
  {
    id: 1,
    senderId: 1,
    senderName: "Ahmed Hassan",
    senderInitials: "AH",
    senderColor: "from-green-500 to-green-600",
    recipientIds: [2, 3, 4, 6],
    recipientNames: ["Fatima Ali", "Omar Mohamed", "Amina Yusuf", "Sara Ibrahim"],
    recipientRole: "All",
    subject: "Day 3 Distribution Schedule Update",
    content: "Team, we need to adjust the distribution schedule for Day 3. Block C will now start at 5:30 PM instead of 6:00 PM due to the expected crowd size.",
    priority: "High",
    status: "Delivered",
    isRead: true,
    isPinned: true,
    isAnnouncement: false,
    date: "Jul 21, 2026",
    time: "2:30 PM",
    attachments: [
      { name: "schedule-day3.pdf", type: "document", size: "245 KB" },
    ],
    thread: [
      {
        id: 1,
        senderId: 1,
        senderName: "Ahmed Hassan",
        senderInitials: "AH",
        senderColor: "from-green-500 to-green-600",
        content: "Team, we need to adjust the distribution schedule for Day 3. Block C will now start at 5:30 PM instead of 6:00 PM due to the expected crowd size.",
        date: "Jul 21, 2026",
        time: "2:30 PM",
      },
      {
        id: 2,
        senderId: 2,
        senderName: "Fatima Ali",
        senderInitials: "FA",
        senderColor: "from-gold-400 to-gold-500",
        content: "Noted. I'll update the Block B schedule as well to coordinate. Should we also increase the volunteer count?",
        date: "Jul 21, 2026",
        time: "2:45 PM",
      },
      {
        id: 3,
        senderId: 1,
        senderName: "Ahmed Hassan",
        senderInitials: "AH",
        senderColor: "from-green-500 to-green-600",
        content: "Yes, let's add 5 more volunteers to Block C. Please coordinate with Sara.",
        date: "Jul 21, 2026",
        time: "3:00 PM",
      },
    ],
  },
  {
    id: 2,
    senderId: 2,
    senderName: "Fatima Ali",
    senderInitials: "FA",
    senderColor: "from-gold-400 to-gold-500",
    recipientIds: [1, 3, 4, 6],
    recipientNames: ["Ahmed Hassan", "Omar Mohamed", "Amina Yusuf", "Sara Ibrahim"],
    recipientRole: "All",
    subject: "Volunteer Training Session - Day 4 Prep",
    content: "Reminder: We have a volunteer training session tomorrow at 3:00 PM at Block D. All team leads please attend to review the distribution process.",
    priority: "Medium",
    status: "Read",
    isRead: true,
    isPinned: false,
    isAnnouncement: false,
    date: "Jul 22, 2026",
    time: "10:15 AM",
    attachments: [],
    thread: [
      {
        id: 1,
        senderId: 2,
        senderName: "Fatima Ali",
        senderInitials: "FA",
        senderColor: "from-gold-400 to-gold-500",
        content: "Reminder: We have a volunteer training session tomorrow at 3:00 PM at Block D. All team leads please attend to review the distribution process.",
        date: "Jul 22, 2026",
        time: "10:15 AM",
      },
      {
        id: 2,
        senderId: 6,
        senderName: "Sara Ibrahim",
        senderInitials: "SI",
        senderColor: "from-blue-400 to-blue-500",
        content: "I'll be there. Should I bring the training materials?",
        date: "Jul 22, 2026",
        time: "10:30 AM",
      },
    ],
  },
  {
    id: 3,
    senderId: 1,
    senderName: "Ahmed Hassan",
    senderInitials: "AH",
    senderColor: "from-green-500 to-green-600",
    recipientIds: [2, 3, 4, 5, 6, 7, 8],
    recipientNames: ["Fatima Ali", "Omar Mohamed", "Amina Yusuf", "Hassan Abdi", "Sara Ibrahim", "Abdirahman Ali", "Khalid Osman"],
    recipientRole: "All",
    subject: "CAMPAIGN ANNOUNCEMENT: Final Day Grand Iftar",
    content: "Important announcement: The final day Grand Iftar will be held at Block E Park. We expect 3,000+ community members. All volunteers must arrive by 2:00 PM. This is our biggest event of the campaign!",
    priority: "Urgent",
    status: "Delivered",
    isRead: false,
    isPinned: true,
    isAnnouncement: true,
    date: "Jul 23, 2026",
    time: "8:00 AM",
    attachments: [
      { name: "final-day-plan.pdf", type: "document", size: "1.2 MB" },
      { name: "venue-map.jpg", type: "image", size: "850 KB" },
    ],
    thread: [
      {
        id: 1,
        senderId: 1,
        senderName: "Ahmed Hassan",
        senderInitials: "AH",
        senderColor: "from-green-500 to-green-600",
        content: "Important announcement: The final day Grand Iftar will be held at Block E Park. We expect 3,000+ community members. All volunteers must arrive by 2:00 PM. This is our biggest event of the campaign!",
        date: "Jul 23, 2026",
        time: "8:00 AM",
      },
    ],
  },
  {
    id: 4,
    senderId: 4,
    senderName: "Amina Yusuf",
    senderInitials: "AY",
    senderColor: "from-gold-400 to-gold-500",
    recipientIds: [1, 2],
    recipientNames: ["Ahmed Hassan", "Fatima Ali"],
    recipientRole: "Managers",
    subject: "Block D Budget Request",
    content: "Hi managers, I need additional budget for Block D school yard. We need extra tables and chairs for the expanded seating area. Estimated cost: $450.",
    priority: "Medium",
    status: "Read",
    isRead: true,
    isPinned: false,
    isAnnouncement: false,
    date: "Jul 22, 2026",
    time: "4:20 PM",
    attachments: [
      { name: "budget-breakdown.xlsx", type: "document", size: "120 KB" },
    ],
    thread: [
      {
        id: 1,
        senderId: 4,
        senderName: "Amina Yusuf",
        senderInitials: "AY",
        senderColor: "from-gold-400 to-gold-500",
        content: "Hi managers, I need additional budget for Block D school yard. We need extra tables and chairs for the expanded seating area. Estimated cost: $450.",
        date: "Jul 22, 2026",
        time: "4:20 PM",
      },
      {
        id: 2,
        senderId: 1,
        senderName: "Ahmed Hassan",
        senderInitials: "AH",
        senderColor: "from-green-500 to-green-600",
        content: "Approved. Please share the vendor details with Fatima for processing.",
        date: "Jul 22, 2026",
        time: "4:45 PM",
      },
    ],
  },
  {
    id: 5,
    senderId: 3,
    senderName: "Omar Mohamed",
    senderInitials: "OM",
    senderColor: "from-blue-400 to-blue-500",
    recipientIds: [1, 2, 4, 6],
    recipientNames: ["Ahmed Hassan", "Fatima Ali", "Amina Yusuf", "Sara Ibrahim"],
    recipientRole: "All",
    subject: "Block C Photography Collection Complete",
    content: "Hi team, I've completed the photography collection for Block C. All 12 photos and 3 videos are uploaded to the gallery. Ready for the campaign report.",
    priority: "Low",
    status: "Read",
    isRead: true,
    isPinned: false,
    isAnnouncement: false,
    date: "Jul 21, 2026",
    time: "7:00 PM",
    attachments: [],
    thread: [
      {
        id: 1,
        senderId: 3,
        senderName: "Omar Mohamed",
        senderInitials: "OM",
        senderColor: "from-blue-400 to-blue-500",
        content: "Hi team, I've completed the photography collection for Block C. All 12 photos and 3 videos are uploaded to the gallery. Ready for the campaign report.",
        date: "Jul 21, 2026",
        time: "7:00 PM",
      },
    ],
  },
  {
    id: 6,
    senderId: 6,
    senderName: "Sara Ibrahim",
    senderInitials: "SI",
    senderColor: "from-blue-400 to-blue-500",
    recipientIds: [1, 2, 4],
    recipientNames: ["Ahmed Hassan", "Fatima Ali", "Amina Yusuf"],
    recipientRole: "Leaders",
    subject: "Volunteer Attendance Issue",
    content: "We had 3 volunteers call in sick today for Block C. We managed with available staff but this could be a problem for the final day. Should we activate the backup volunteer list?",
    priority: "High",
    status: "Sent",
    isRead: false,
    isPinned: false,
    isAnnouncement: false,
    date: "Jul 23, 2026",
    time: "9:15 AM",
    attachments: [],
    thread: [
      {
        id: 1,
        senderId: 6,
        senderName: "Sara Ibrahim",
        senderInitials: "SI",
        senderColor: "from-blue-400 to-blue-500",
        content: "We had 3 volunteers call in sick today for Block C. We managed with available staff but this could be a problem for the final day. Should we activate the backup volunteer list?",
        date: "Jul 23, 2026",
        time: "9:15 AM",
      },
    ],
  },
  {
    id: 7,
    senderId: 7,
    senderName: "Abdirahman Ali",
    senderInitials: "AA",
    senderColor: "from-purple-400 to-purple-500",
    recipientIds: [1, 2],
    recipientNames: ["Ahmed Hassan", "Fatima Ali"],
    recipientRole: "Managers",
    subject: "Equipment Inventory Report",
    content: "Here's the weekly equipment inventory report. We're running low on serving trays (15 remaining) and need to order more water containers.",
    priority: "Medium",
    status: "Delivered",
    isRead: false,
    isPinned: false,
    isAnnouncement: false,
    date: "Jul 23, 2026",
    time: "11:00 AM",
    attachments: [
      { name: "inventory-report.xlsx", type: "document", size: "95 KB" },
    ],
    thread: [
      {
        id: 1,
        senderId: 7,
        senderName: "Abdirahman Ali",
        senderInitials: "AA",
        senderColor: "from-purple-400 to-purple-500",
        content: "Here's the weekly equipment inventory report. We're running low on serving trays (15 remaining) and need to order more water containers.",
        date: "Jul 23, 2026",
        time: "11:00 AM",
      },
    ],
  },
  {
    id: 8,
    senderId: 1,
    senderName: "Ahmed Hassan",
    senderInitials: "AH",
    senderColor: "from-green-500 to-green-600",
    recipientIds: [2, 3, 4, 5, 6, 7, 8],
    recipientNames: ["Fatima Ali", "Omar Mohamed", "Amina Yusuf", "Hassan Abdi", "Sara Ibrahim", "Abdirahman Ali", "Khalid Osman"],
    recipientRole: "All",
    subject: "CAMPAIGN ANNOUNCEMENT: Day 5 Safety Protocol",
    content: "Safety reminder for all volunteers: Please ensure all food handling follows hygiene standards. First aid stations will be available at each block. Report any incidents immediately.",
    priority: "Urgent",
    status: "Read",
    isRead: true,
    isPinned: false,
    isAnnouncement: true,
    date: "Jul 23, 2026",
    time: "7:30 AM",
    attachments: [],
    thread: [
      {
        id: 1,
        senderId: 1,
        senderName: "Ahmed Hassan",
        senderInitials: "AH",
        senderColor: "from-green-500 to-green-600",
        content: "Safety reminder for all volunteers: Please ensure all food handling follows hygiene standards. First aid stations will be available at each block. Report any incidents immediately.",
        date: "Jul 23, 2026",
        time: "7:30 AM",
      },
    ],
  },
  {
    id: 9,
    senderId: 8,
    senderName: "Khalid Osman",
    senderInitials: "KO",
    senderColor: "from-rose-400 to-rose-500",
    recipientIds: [1, 2],
    recipientNames: ["Ahmed Hassan", "Fatima Ali"],
    recipientRole: "Managers",
    subject: "Block E Park Setup Status",
    content: "Setup at Block E Park is 70% complete. We've secured the perimeter and set up the main stage. Lighting and sound will be installed tomorrow morning.",
    priority: "Low",
    status: "Delivered",
    isRead: false,
    isPinned: false,
    isAnnouncement: false,
    date: "Jul 23, 2026",
    time: "1:00 PM",
    attachments: [
      { name: "setup-progress.jpg", type: "image", size: "2.1 MB" },
      { name: "setup-progress-2.jpg", type: "image", size: "1.8 MB" },
    ],
    thread: [
      {
        id: 1,
        senderId: 8,
        senderName: "Khalid Osman",
        senderInitials: "KO",
        senderColor: "from-rose-400 to-rose-500",
        content: "Setup at Block E Park is 70% complete. We've secured the perimeter and set up the main stage. Lighting and sound will be installed tomorrow morning.",
        date: "Jul 23, 2026",
        time: "1:00 PM",
      },
    ],
  },
  {
    id: 10,
    senderId: 2,
    senderName: "Fatima Ali",
    senderInitials: "FA",
    senderColor: "from-gold-400 to-gold-500",
    recipientIds: [3, 6],
    recipientNames: ["Omar Mohamed", "Sara Ibrahim"],
    recipientRole: "Volunteers",
    subject: "Thank You - Block B Success",
    content: "Amazing work everyone! Block B served 2,800 meals today, our highest single-day record. Thank you all for your dedication and hard work. Special thanks to the cooking team!",
    priority: "Low",
    status: "Read",
    isRead: true,
    isPinned: true,
    isAnnouncement: false,
    date: "Jul 20, 2026",
    time: "9:00 PM",
    attachments: [
      { name: "block-b-group-photo.jpg", type: "image", size: "3.5 MB" },
      { name: "iftar-highlights.mp4", type: "video", size: "45.2 MB" },
    ],
    thread: [
      {
        id: 1,
        senderId: 2,
        senderName: "Fatima Ali",
        senderInitials: "FA",
        senderColor: "from-gold-400 to-gold-500",
        content: "Amazing work everyone! Block B served 2,800 meals today, our highest single-day record. Thank you all for your dedication and hard work. Special thanks to the cooking team!",
        date: "Jul 20, 2026",
        time: "9:00 PM",
      },
      {
        id: 2,
        senderId: 3,
        senderName: "Omar Mohamed",
        senderInitials: "OM",
        senderColor: "from-blue-400 to-blue-500",
        content: "Great teamwork! The distribution went smoothly.",
        date: "Jul 20, 2026",
        time: "9:15 PM",
      },
    ],
  },
];

export const sidebarNav = [
  { label: "Dashboard", icon: "dashboard", href: "/dashboard", active: true },
  { label: "Users", icon: "users", href: "/dashboard/users", active: false },
  {
    label: "Donations",
    icon: "donations",
    href: "/dashboard/donations",
    active: false,
  },
  {
    label: "Expenses",
    icon: "expenses",
    href: "/dashboard/expenses",
    active: false,
  },
  {
    label: "Daily Reports",
    icon: "reports",
    href: "/dashboard/reports",
    active: false,
  },
  { label: "Tasks", icon: "tasks", href: "/dashboard/tasks", active: false },
  { label: "Gallery", icon: "gallery", href: "/dashboard/gallery", active: false },
  {
    label: "Messages",
    icon: "messages",
    href: "/dashboard/messages",
    active: false,
  },
  {
    label: "Analytics",
    icon: "analytics",
    href: "/dashboard/analytics",
    active: false,
  },
  {
    label: "Settings",
    icon: "settings",
    href: "/dashboard/settings",
    active: false,
  },
];
